### ISSUE TITLE
Doesn't seem to be working nicely with Pact Slots

### ISSUE THREAD

**Issue by Battenhatch** [misthero/dnd5e-spellpoints#28] opened 2022-05-02 06:14 UTC
Hi

When this module is installed, the Pact slots a multiclass Warlock has, do not show correctly in the slot choosing option, and are not expended when chosen. The first image shows the standard spell slots options, and the second one is with the spell points module installed.
![spellslots](https://user-images.githubusercontent.com/24476876/166192140-51f99003-5b6e-416b-a44c-7068298e613c.jpg)
![spellpoints](https://user-images.githubusercontent.com/24476876/166192144-222dfd36-3d68-4c78-9a26-a6cce1c1886e.jpg)
.

**Comment by misthero** [comment] 2022-05-02 09:29
Thx, I'll investigate

**Comment by Battenhatch** [comment] 2022-05-02 12:54
Waitjustag**d***minute! Now it seems to be doing fine! That's odd. Must have been a refreshing issue.

**Comment by misthero** [comment] 2022-05-02 20:03
ok than, I'm closing the issue, if you notice any other bug just open a new one.

**Comment by CrackJackFlood** [comment] 2022-05-31 17:47
> Waitjustag**d***minute! Now it seems to be doing fine! That's odd. Must have been a refreshing issue.

Do you have any idea how you fixed this?

**Comment by Battenhatch** [comment] 2022-06-01 06:10
Actually, the problem has resurface at my end and I'll try to sort it out. I'm beginnig to think it's some sort of module conflict, perhaps, so I'll try a bit of "Finding the Culprit" soon.

**Comment by misthero** [comment] 2022-06-01 06:56
@CrackJackFlood and @Battenhatch 

continue the issue here please.

Looks like the issue is related with the spells labeled with progression "pact" and I'm going to find a solution. Anyway this module is born to completely replace slots with spell points, but in base rules warlocks cannot use the spellpoint system.

So I'm going to ask you two what is your usecase, do you want the "pact" magic keep using slots or shoult it use spellpoints?

This is an issue now in case of multiclassing, since with mixed mode you can disable the spellpoints for a warlock caster, but a druid/warlock, or any other caster/warlock combination will cause problems.

**Comment by Battenhatch** [comment] 2022-06-01 07:25
For me, keeping the Pact Slots works best. The Warlocks are their own thing, with the short rest recovery and all.

**Comment by CrackJackFlood** [comment] 2022-06-02 05:33
@misthero 

I recommend you reexamine the whole module as there quite a few bugs which are seemingly due to the 1.6.1 changes.

Personally I would like spell points and pact slots to function like RAW/RAI, meaning they are separate but I can see people wanting options given spell points are a variant rule.

I am a bit confused on the issue of multicasting, shouldn't spell points and spell slots function the same here when it comes to pact slots?

**Comment by misthero** [comment] 2022-06-02 20:56
new version is out that also adds new features should fix this issue
https://github.com/misthero/dnd5e-spellpoints/commit/31fe27081399525df6b8dedbd35b032a6adbdae6

@CrackJackFlood about the other bugs you see please kindly fill an issue so I can check it.

Thank you.

**Comment by Battenhatch** [comment] 2022-06-03 05:42
At first glance, it seems to be working very nicely :). Thanks.

**Comment by misthero** [comment] 2022-06-04 15:23
closing as fixed

**Closed by misthero** 2022-06-04 15:23 UTC
Labels: bug, Work in Progress
